# Data Cleaning
> Objectives:
    - Given a messy dataset - extract meaningful information from it. 
    - Learn from the data.

In [75]:
import pandas as pd
import numpy as np

In [ ]:
# read vehicles_messy.csv
# quick analysis
# display more columns on the dataframe visualization

## Data types

### Checking data types of our dataset

In [76]:
pd.set_option('display.max_columns',None)

In [4]:
pd.set_option('display.max_rows',60)

In [6]:
# Your code here!
df = pd.read_csv("vehicles_messy.csv", dtype={'year':'object'})

/var/folders/4s/j3x9y61j1gj2zdqsyf0tqv0w0000gn/T/ipykernel_3412/3550249580.py:2: DtypeWarning: Columns (70,71,72,73,74,76,79) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("vehicles_messy.csv", dtype={'year':'object'})

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 83 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   barrels08        37843 non-null  float64
 1   barrelsA08       37843 non-null  float64
 2   charge120        37843 non-null  float64
 3   charge240        37843 non-null  float64
 4   city08           37843 non-null  int64
 5   city08U          37843 non-null  float64
 6   cityA08          37843 non-null  int64
 7   cityA08U         37843 non-null  float64
 8   cityCD           37843 non-null  float64
 9   cityE            37843 non-null  float64
 10  cityUF           37843 non-null  float64
 11  co2              37843 non-null  int64
 12  co2A             37843 non-null  int64
 13  co2TailpipeAGpm  37843 non-null  float64
 14  co2TailpipeGpm   37843 non-null  float64
 15  comb08           37843 non-null  int64
 16  comb08U          37843 non-null  float64
 17  combA08          37843 non-null  int64
 18  combA08U         37843 non-null  float64
 19  combE            37843 non-null  float64
 20  combinedCD       37843 non-null  float64
 21  combinedUF       37843 non-null  float64
 22  cylinders        37720 non-null  float64
 23  displ            37723 non-null  float64
 24  drive            36654 non-null  object
 25  engId            37843 non-null  int64
 26  eng_dscr         22440 non-null  object
 27  feScore          37843 non-null  int64
 28  fuelCost08       37843 non-null  int64
 29  fuelCostA08      37843 non-null  int64
 30  fuelType         37843 non-null  object
 31  fuelType1        37843 non-null  object
 32  ghgScore         37843 non-null  int64
 33  ghgScoreA        37843 non-null  int64
 34  highway08        37843 non-null  int64
 35  highway08U       37843 non-null  float64
 36  highwayA08       37843 non-null  int64
 37  highwayA08U      37843 non-null  float64
 38  highwayCD        37843 non-null  float64
 39  highwayE         37843 non-null  float64
 40  highwayUF        37843 non-null  float64
 41  hlv              37843 non-null  int64
 42  hpv              37843 non-null  int64
 43  id               37843 non-null  int64
 44  lv2              37843 non-null  int64
 45  lv4              37843 non-null  int64
 46  make             37843 non-null  object
 47  model            37843 non-null  object
 48  mpgData          37843 non-null  object
 49  phevBlended      37843 non-null  bool
 50  pv2              37843 non-null  int64
 51  pv4              37843 non-null  int64
 52  range            37843 non-null  int64
 53  rangeCity        37843 non-null  float64
 54  rangeCityA       37843 non-null  float64
 55  rangeHwy         37843 non-null  float64
 56  rangeHwyA        37843 non-null  float64
 57  trany            37832 non-null  object
 58  UCity            37843 non-null  float64
 59  UCityA           37843 non-null  float64
 60  UHighway         37843 non-null  float64
 61  UHighwayA        37843 non-null  float64
 62  VClass           37843 non-null  object
 63  year             37843 non-null  object
 64  youSaveSpend     37843 non-null  int64
 65  guzzler          2281 non-null   object
 66  trans_dscr       15047 non-null  object
 67  tCharger         5186 non-null   object
 68  sCharger         666 non-null    object
 69  atvType          3072 non-null   object
 70  fuelType2        1408 non-null   object
 71  rangeA           1403 non-null   object
 72  evMotor          562 non-null    object
 73  mfrCode          7025 non-null   object
 74  c240Dscr         37 non-null     object
 75  charge240b       37843 non-null  float64
 76  c240bDscr        36 non-null     object
 77  createdOn        37843 non-null  object
 78  modifiedOn       37843 non-null  object
 79  startStop        6138 non-null   object
 80  phevCity         37843 non-null  int64
 81  phevHwy          37843 non-null  int64
 82  phevComb         37843 non-null  int64
dtypes: bool(1), float64(32), int64(26), object(24)
memory usage: 23.7+ MB

In [14]:
type(df.dtypes)

pandas.core.series.Series

In [20]:
df.select_dtypes(include='object').head()

,drive,eng_dscr,fuelType,fuelType1,make,model,mpgData,trany,VClass,year,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,c240bDscr,createdOn,modifiedOn,startStop
0,Rear-Wheel Drive,(FFS),Regular,Regular Gasoline,Alfa Romeo,Spider Veloce 2000,Y,Manual 5-spd,Two Seaters,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN
1,Rear-Wheel Drive,(GUZZLER),Regular,Regular Gasoline,Ferrari,Testarossa,N,Manual 5-spd,Two Seaters,1985,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN
2,Front-Wheel Drive,(FFS),Regular,Regular Gasoline,Dodge,Charger,Y,Manual 5-spd,Subcompact Cars,1985,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN
3,Rear-Wheel Drive,NaN,Regular,Regular Gasoline,Dodge,B150/B250 Wagon 2WD,N,Automatic 3-spd,Vans,1985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN
4,4-Wheel or All-Wheel Drive,"(FFS,TRBO)",Premium,Premium Gasoline,Subaru,Legacy AWD Turbo,N,Manual 5-spd,Compact Cars,1993,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN

In [19]:
df.select_dtypes(include='object').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   drive       36654 non-null  object
 1   eng_dscr    22440 non-null  object
 2   fuelType    37843 non-null  object
 3   fuelType1   37843 non-null  object
 4   make        37843 non-null  object
 5   model       37843 non-null  object
 6   mpgData     37843 non-null  object
 7   trany       37832 non-null  object
 8   VClass      37843 non-null  object
 9   year        37843 non-null  object
 10  guzzler     2281 non-null   object
 11  trans_dscr  15047 non-null  object
 12  tCharger    5186 non-null   object
 13  sCharger    666 non-null    object
 14  atvType     3072 non-null   object
 15  fuelType2   1408 non-null   object
 16  rangeA      1403 non-null   object
 17  evMotor     562 non-null    object
 18  mfrCode     7025 non-null   object
 19  c240Dscr    37 non-null     object
 20  c240bDscr   36 non-null     object
 21  createdOn   37843 non-null  object
 22  modifiedOn  37843 non-null  object
 23  startStop   6138 non-null   object
dtypes: object(24)
memory usage: 6.9+ MB

In [27]:
df.dtypes[df.dtypes == 'object']

drive         object
eng_dscr      object
fuelType      object
fuelType1     object
make          object
model         object
mpgData       object
trany         object
VClass        object
guzzler       object
trans_dscr    object
tCharger      object
sCharger      object
atvType       object
fuelType2     object
rangeA        object
evMotor       object
mfrCode       object
c240Dscr      object
c240bDscr     object
createdOn     object
modifiedOn    object
startStop     object
dtype: object

### Convert values using `.astype()`

Converts the type of the column

In [ ]:
df['year'] = df['year'].astype('int')

### Convert values using map

In [28]:
df['year'] = df['year'].astype('str')

In [29]:
df['year'].map(int) ## atenção: MAP transforma qualquer função em "metodo" de pandas DataFrame

0        1985
1        1985
2        1985
3        1985
4        1993
         ...
37838    1993
37839    1993
37840    1993
37841    1993
37842    1993
Name: year, Length: 37843, dtype: int64

In [38]:
np.nan

nan

In [45]:
def int_forcado(ano):
    try:
        return int(ano)
    except:
        return np.nan

In [ ]:
['1985', '1986', '1987', 'Renata', '1988']

In [40]:
df_year = pd.DataFrame(['1985', '1986', '1987', 'Renata', '1988'], columns=['year'])

In [41]:
df_year

     year
0    1985
1    1986
2    1987
3  Renata
4    1988

In [48]:
# df_year.astype('int')
df_year['year'].map(int_forcado)

0    1985.0
1    1986.0
2    1987.0
3       NaN
4    1988.0
Name: year, dtype: float64

In [33]:
def classif_ano(ano):
    if int(ano) <= 1990:
        return 'A'
    else:
        return 'B'

In [34]:
classif_ano(1885)

'A'

In [35]:
df['year_classif'] = df['year'].map(classif_ano)

0        A
1        A
2        A
3        A
4        B
        ..
37838    B
37839    B
37840    B
37841    B
37842    B
Name: year, Length: 37843, dtype: object

## Null (or missing) values

>    - Called NaN: <u>Not A Number</u>
>    - Count 
>    - <b>Mask</b> concept

### `np.nan`

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37843 entries, 0 to 37842
Data columns (total 83 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   barrels08        37843 non-null  float64
 1   barrelsA08       37843 non-null  float64
 2   charge120        37843 non-null  float64
 3   charge240        37843 non-null  float64
 4   city08           37843 non-null  int64
 5   city08U          37843 non-null  float64
 6   cityA08          37843 non-null  int64
 7   cityA08U         37843 non-null  float64
 8   cityCD           37843 non-null  float64
 9   cityE            37843 non-null  float64
 10  cityUF           37843 non-null  float64
 11  co2              37843 non-null  int64
 12  co2A             37843 non-null  int64
 13  co2TailpipeAGpm  37843 non-null  float64
 14  co2TailpipeGpm   37843 non-null  float64
 15  comb08           37843 non-null  int64
 16  comb08U          37843 non-null  float64
 17  combA08          37843 non-null  int64
 18  combA08U         37843 non-null  float64
 19  combE            37843 non-null  float64
 20  combinedCD       37843 non-null  float64
 21  combinedUF       37843 non-null  float64
 22  cylinders        37720 non-null  float64
 23  displ            37723 non-null  float64
 24  drive            36654 non-null  object
 25  engId            37843 non-null  int64
 26  eng_dscr         22440 non-null  object
 27  feScore          37843 non-null  int64
 28  fuelCost08       37843 non-null  int64
 29  fuelCostA08      37843 non-null  int64
 30  fuelType         37843 non-null  object
 31  fuelType1        37843 non-null  object
 32  ghgScore         37843 non-null  int64
 33  ghgScoreA        37843 non-null  int64
 34  highway08        37843 non-null  int64
 35  highway08U       37843 non-null  float64
 36  highwayA08       37843 non-null  int64
 37  highwayA08U      37843 non-null  float64
 38  highwayCD        37843 non-null  float64
 39  highwayE         37843 non-null  float64
 40  highwayUF        37843 non-null  float64
 41  hlv              37843 non-null  int64
 42  hpv              37843 non-null  int64
 43  id               37843 non-null  int64
 44  lv2              37843 non-null  int64
 45  lv4              37843 non-null  int64
 46  make             37843 non-null  object
 47  model            37843 non-null  object
 48  mpgData          37843 non-null  object
 49  phevBlended      37843 non-null  bool
 50  pv2              37843 non-null  int64
 51  pv4              37843 non-null  int64
 52  range            37843 non-null  int64
 53  rangeCity        37843 non-null  float64
 54  rangeCityA       37843 non-null  float64
 55  rangeHwy         37843 non-null  float64
 56  rangeHwyA        37843 non-null  float64
 57  trany            37832 non-null  object
 58  UCity            37843 non-null  float64
 59  UCityA           37843 non-null  float64
 60  UHighway         37843 non-null  float64
 61  UHighwayA        37843 non-null  float64
 62  VClass           37843 non-null  object
 63  year             37843 non-null  object
 64  youSaveSpend     37843 non-null  int64
 65  guzzler          2281 non-null   object
 66  trans_dscr       15047 non-null  object
 67  tCharger         5186 non-null   object
 68  sCharger         666 non-null    object
 69  atvType          3072 non-null   object
 70  fuelType2        1408 non-null   object
 71  rangeA           1403 non-null   object
 72  evMotor          562 non-null    object
 73  mfrCode          7025 non-null   object
 74  c240Dscr         37 non-null     object
 75  charge240b       37843 non-null  float64
 76  c240bDscr        36 non-null     object
 77  createdOn        37843 non-null  object
 78  modifiedOn       37843 non-null  object
 79  startStop        6138 non-null   object
 80  phevCity         37843 non-null  int64
 81  phevHwy          37843 non-null  int64
 82  phevComb         37843 non-null  int64
dtypes: bool(1), float64(32), int64(26), object(24)
memory usage: 23.7+ MB

In [68]:
df.sCharger.isna().value_counts()

True     37177
False      666
Name: sCharger, dtype: int64

In [70]:
df.isna().groupby('sCharger')['sCharger'].count()

sCharger
False      666
True     37177
Name: sCharger, dtype: int64

In [60]:
df.isna()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37838,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
37839,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
37840,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
37841,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False
37842,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,True,True,True,True,False,True,False,False,True,False,False,False

In [55]:
df.sCharger.notnull()

0        False
1        False
2        False
3        False
4        False
         ...
37838    False
37839    False
37840    False
37841    False
37842    False
Name: sCharger, Length: 37843, dtype: bool

In [49]:
type(np.nan)

float

### Let's select the displ column and see how many missing values this column has.

### How to count it how many missing there are?

In [ ]:
#isna() or isnull() as above

In [91]:
(df.isna().sum()*100/df.shape[0]).sort_values(ascending=False).astype('int')

c240bDscr          99
c240Dscr           99
evMotor            98
sCharger           98
rangeA             96
fuelType2          96
guzzler            93
atvType            91
tCharger           86
startStop          83
mfrCode            81
trans_dscr         60
eng_dscr           40
drive               3
cylinders           0
displ               0
trany               0
rangeCity           0
rangeCityA          0
rangeHwy            0
barrels08           0
range               0
pv4                 0
pv2                 0
phevBlended         0
mpgData             0
model               0
make                0
rangeHwyA           0
VClass              0
UCity               0
UCityA              0
UHighway            0
UHighwayA           0
lv2                 0
year                0
youSaveSpend        0
charge240b          0
createdOn           0
modifiedOn          0
phevCity            0
phevHwy             0
lv4                 0
hlv                 0
id                  0
cityUF              0
combA08             0
comb08U             0
comb08              0
co2TailpipeGpm      0
co2TailpipeAGpm     0
co2A                0
co2                 0
cityE               0
combE               0
cityCD              0
cityA08U            0
cityA08             0
city08U             0
city08              0
charge240           0
charge120           0
combA08U            0
combinedCD          0
hpv                 0
highway08           0
barrelsA08          0
highwayUF           0
highwayE            0
highwayCD           0
highwayA08U         0
highwayA08          0
highway08U          0
ghgScoreA           0
combinedUF          0
ghgScore            0
fuelType1           0
fuelType            0
fuelCostA08         0
fuelCost08          0
feScore             0
engId               0
phevComb            0
dtype: int64

In [21]:
serie_nulos = (df.isna().sum()*100/df.shape[0]).sort_values(ascending=False).astype('int')
((serie_nulos > 0).value_counts(normalize=True))

False    0.831325
True     0.168675
dtype: float64

In [22]:
83*0.168675

14.000024999999999

### What if we wanted to count Null values for each row?
    - axis = 1

In [94]:
df.shape

(37843, 83)

In [96]:
df.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [14]:
pd.set_option('display.max_rows', None)

In [16]:
df.isna().sum(axis=1).sort_values(ascending=False).head(30)

18374    14
18812    14
8144     14
18822    14
18541    14
18540    14
7138     14
18235    14
18696    14
18814    14
18236    14
18912    14
21413    14
18885    14
18709    14
19450    14
18888    14
18512    14
18914    14
18516    14
18623    14
18513    14
18543    14
18621    14
18824    14
18828    14
18225    14
18349    14
18227    14
8147     14
dtype: int64

### What if I wanted to select only the rows in which there are at least one missing value (in any column)?

In [26]:
df.isna().sum(axis=1).value_counts(normalize=True).sort_index()

4     0.000053
5     0.000925
6     0.002352
7     0.013054
8     0.016859
9     0.073541
10    0.081204
11    0.282800
12    0.398066
13    0.130196
14    0.000951
dtype: float64

## Dropping columns
> `axis=1` or

> `columns = ['name_of_column_to_drop1', 'name_of_column_to_drop2' ,...]`

### Drop columns based on condition

In [34]:
col_null_perc = df.isna().sum()*100/df.shape[0]
cols2drop = col_null_perc[col_null_perc > 40].index
cols2drop

Index(['eng_dscr', 'guzzler', 'trans_dscr', 'tCharger', 'sCharger', 'atvType',
       'fuelType2', 'rangeA', 'evMotor', 'mfrCode', 'c240Dscr', 'c240bDscr',
       'startStop'],
      dtype='object')

In [36]:
df_notnulls = df.drop(columns=cols2drop)
df_notnulls.shape

(37843, 70)

In [45]:
df_notnulls.isna().sum(axis=1).value_counts().sort_values(ascending=False).head(20)

0    36537
1     1186
2      106
3       11
4        3
dtype: int64

In [ ]:
df_nulllines = df.drop(index=lst_index2drop)

In [ ]:
df_notnulls.description

In [37]:
dir(df_notnulls)

['T',
 'UCity',
 'UCityA',
 'UHighway',
 'UHighwayA',
 'VClass',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'barrels08',
 'barrelsA08',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'charge120',
 'charge240',
 'charge240b',
 'city08',
 'city08U',
 'cityA08',
 'cityA08U',
 'cityCD',
 'cityE',
 'cityUF',
 'clip',
 'co2',
 'co2A',
 'co2TailpipeAGpm',
 'co2TailpipeGpm',
 'columns',
 'comb08',
 'comb08U',
 'combA08',
 'combA08U',
 'combE',
 'combine',
 'combine_first',
 'combinedCD',
 'combinedUF',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'createdOn',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'cylinders',
 'describe',
 'diff',
 'displ',
 'div',
 'divide',
 'dot',
 'drive',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'engId',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'feScore',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'fuelCost08',
 'fuelCostA08',
 'fuelType',
 'fuelType1',
 'ge',
 'get',
 'ghgScore',
 'ghgScoreA',
 'groupby',
 'gt',
 'head',
 'highway08',
 'highway08U',
 'highwayA08',
 'highwayA08U',
 'highwayCD',
 'highwayE',
 'highwayUF',
 'hist',
 'hlv',
 'hpv',
 'iat',
 'id',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'lv2',
 'lv4',
 'mad',
 'make',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'model',
 'modifiedOn',
 'mpgData',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'phevBlended',
 'phevCity',
 'phevComb',
 'phevHwy',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'pv2',
 'pv4',
 'quantile',
 'query',
 'radd',
 'range',
 'rangeCity',
 'rangeCityA',
 'rangeHwy',
 'rangeHwyA',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'trany',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs',
 'year',
 'youSaveSpend']

### Using `dropna`

In [39]:
df.dropna().shape

(0, 83)

In [41]:
df_notnulls.shape

(37843, 70)

In [40]:
df_notnulls.dropna().shape

(36537, 70)

In [44]:
(1 - df_notnulls.dropna().shape[0]/df_notnulls.shape[0])*100

3.451100599846735

In [ ]:
df_notnulls.dropna(how='all')

In [58]:
df.shape[0]*0.60

22705.8

In [57]:
df_notnulls2 = df.dropna(axis=1, thresh=df.shape[0]*0.60)
df_notnulls2.shape

(37843, 70)

In [ ]:
#equiv
col_null_perc = df.isna().sum()*100/df.shape[0]
cols2drop = col_null_perc[col_null_perc > 40].index
cols2drop
df_notnulls = df.drop(columns=cols2drop)

### Fill with some value

In [63]:
df_notnulls.isna().sum().sort_values(ascending=False).head()

drive        1189
cylinders     123
displ         120
trany          11
barrels08       0
dtype: int64

In [ ]:
df_notnulls.v

In [66]:
df_notnulls.head()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
0,15.695714,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,-1,1600,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-1250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
1,29.964545,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,-1,3050,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
2,12.207778,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,-1,1250,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
3,29.964545,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,-1,3050,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-8500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
4,17.347895,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,-1,2150,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-4000,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0

In [69]:
df.co2.value_counts()

-1      31989
 0        120
 413       66
 382       41
 344       41
 358       41
 354       41
 374       41
 425       39
 317       38
 301       37
 386       36
 475       35
 521       34
 357       34
 405       33
 444       33
 323       33
 385       32
 295       32
 343       32
 340       32
 408       31
 523       31
 375       31
 346       31
 377       30
 324       30
 404       30
 349       30
 486       30
 288       30
 398       29
 432       29
 312       29
 313       29
 379       29
 517       28
 334       28
 465       28
 468       28
 481       28
 437       27
 372       27
 328       27
 397       27
 302       27
 458       27
 476       27
 373       27
 442       26
 407       26
 387       26
 470       26
 361       26
 337       25
 389       25
 376       25
 423       25
 424       25
 482       25
 370       25
 459       25
 392       25
 418       25
 426       24
 339       24
 297       24
 369       24
 314       24
 360       23
 410       23
 446       23
 460       23
 477       23
 395       23
 345       23
 429       23
 318       23
 412       22
 388       22
 417       22
 480       22
 362       22
 338       22
 499       22
 307       22
 396       22
 309       22
 342       22
 325       22
 393       21
 390       21
 554       21
 353       21
 330       21
 401       21
 421       21
 462       20
 439       20
 448       20
 478       20
 420       20
 293       20
 310       20
 427       20
 367       20
 430       20
 335       20
 305       20
 322       20
 419       20
 415       20
 341       20
 321       19
 399       19
 368       19
 406       19
 333       19
 291       19
 289       19
 414       19
 384       18
 457       18
 271       18
 402       18
 403       18
 440       18
 428       18
 316       18
 498       18
 400       17
 286       17
 350       17
 416       17
 281       17
 298       17
 445       17
 285       17
 371       17
 287       17
 394       17
 449       17
 441       17
 621       16
 488       16
 604       16
 450       16
 454       16
 447       16
 332       16
 383       16
 503       16
 433       16
 537       16
 308       15
 456       15
 434       15
 487       15
 494       15
 359       15
 489       15
 463       15
 391       15
 355       15
 319       15
 500       15
 490       15
 622       15
 275       15
 378       14
 443       14
 260       14
 464       14
 581       14
 466       14
 504       14
 580       14
 296       14
 527       14
 452       14
 292       14
 592       14
 518       14
 326       14
 493       14
 474       13
 336       13
 299       13
 495       13
 637       13
 455       13
 347       13
 300       13
 551       13
 422       13
 351       13
 320       13
 409       13
 431       12
 436       12
 557       12
 473       12
 471       12
 277       12
 315       12
 453       12
 365       11
 479       11
 467       11
 638       11
 615       11
 284       11
 303       11
 381       11
 612       11
 306       11
 356       11
 534       11
 366       10
 363       10
 502       10
 519       10
 294       10
 238       10
 438       10
 538       10
 483       10
 327       10
 282       10
 710       10
 532       10
 311       10
 491       10
 601       10
 304        9
 484        9
 587        9
 461        9
 507        9
 276        9
 611        9
 497        9
 469        9
 348        9
 572        9
 290        9
 472        9
 329        9
 352        9
 525        8
 675        8
 555        8
 556        8
 501        8
 280        8
 129        8
 548        8
 552        8
 283        8
 265        8
 364        8
 278        8
 237        8
 269        8
 211        8
 596        8
 560        8
 273        8
 511        8
 520        8
 223        7
 529        7
 411        7
 588        7
 570        7
 512        7
 279        7
 582        7
 505        7
 247        7
 574        7
 564        7
 222        7
 485        7
 515        7
 435        7
 506        6
 671        6
 526        6
 533        6
 562        6
 608        6
 549        6
 547        6
 224        6
 613        6
 697        6
 747        6
 676        6
 546        6
 270        6
 571        6
 524        6
 531        6
 508        6
 569        6
 628        6
 331        6
 451        6
 620        5
 266        5
 264        5
 566        5
 255        5
 539        5
 669        5
 577        5
 200        5
 215        5
 595        5
 380        5
 623        5
 553        5
 242        5
 558        5
 626        5
 578        5
 496        5
 576        5
 209        5
 268        5
 565        5
 720        5
 259        5
 133        4
 239        4
 630        4
 684        4
 579        4
 257        4
 261        4
 516        4
 627        4
 514        4
 617        4
 244        4
 178        4
 696        4
 179        4
 522        4
 258        4
 256        4
 634        4
 263        4
 618        4
 267        4
 692        4
 679        4
 609        4
 528        4
 198        3
 91         3
 536        3
 540        3
 641        3
 805        3
 196        3
 544        3
 716        3
 212        3
 253        3
 243        3
 272        3
 158        3
 542        3
 225        3
 686        3
 568        3
 646        3
 847        3
 614        3
 274        3
 586        3
 688        3
 605        3
 81         3
 559        3
 625        3
 643        3
 645        3
 610        3
 584        3
 249        3
 606        3
 639        3
 742        3
 218        3
 633        2
 718        2
 704        2
 229        2
 40         2
 492        2
 740        2
 721        2
 221        2
 711        2
 545        2
 104        2
 731        2
 252        2
 543        2
 677        2
 513        2
 251        2
 51         2
 227        2
 535        2
 717        2
 262        2
 607        2
 602        2
 650        2
 647        2
 254        2
 188        2
 541        2
 763        2
 600        2
 680        2
 210        2
 228        2
 681        2
 233        2
 130        1
 619        1
 84         1
 698        1
 112        1
 217        1
 226        1
 184        1
 672        1
 662        1
 674        1
 661        1
 659        1
 183        1
 230        1
 530        1
 652        1
 214        1
 683        1
 171        1
 189        1
 194        1
 594        1
 624        1
 724        1
 250        1
 762        1
 241        1
 220        1
 206        1
 678        1
 668        1
 169        1
 664        1
 723        1
 561        1
 567        1
 583        1
 790        1
 591        1
 656        1
 727        1
 37         1
 636        1
 599        1
 563        1
 590        1
 246        1
 101        1
 593        1
 801        1
 663        1
 87         1
 138        1
 170        1
 248        1
Name: co2, dtype: int64

In [68]:
df_notnulls.co2.value_counts()

-1      31989
 0        120
 413       66
 382       41
 344       41
 358       41
 354       41
 374       41
 425       39
 317       38
 301       37
 386       36
 475       35
 521       34
 357       34
 405       33
 444       33
 323       33
 385       32
 295       32
 343       32
 340       32
 408       31
 523       31
 375       31
 346       31
 377       30
 324       30
 404       30
 349       30
 486       30
 288       30
 398       29
 432       29
 312       29
 313       29
 379       29
 517       28
 334       28
 465       28
 468       28
 481       28
 437       27
 372       27
 328       27
 397       27
 302       27
 458       27
 476       27
 373       27
 442       26
 407       26
 387       26
 470       26
 361       26
 337       25
 389       25
 376       25
 423       25
 424       25
 482       25
 370       25
 459       25
 392       25
 418       25
 426       24
 339       24
 297       24
 369       24
 314       24
 360       23
 410       23
 446       23
 460       23
 477       23
 395       23
 345       23
 429       23
 318       23
 412       22
 388       22
 417       22
 480       22
 362       22
 338       22
 499       22
 307       22
 396       22
 309       22
 342       22
 325       22
 393       21
 390       21
 554       21
 353       21
 330       21
 401       21
 421       21
 462       20
 439       20
 448       20
 478       20
 420       20
 293       20
 310       20
 427       20
 367       20
 430       20
 335       20
 305       20
 322       20
 419       20
 415       20
 341       20
 321       19
 399       19
 368       19
 406       19
 333       19
 291       19
 289       19
 414       19
 384       18
 457       18
 271       18
 402       18
 403       18
 440       18
 428       18
 316       18
 498       18
 400       17
 286       17
 350       17
 416       17
 281       17
 298       17
 445       17
 285       17
 371       17
 287       17
 394       17
 449       17
 441       17
 621       16
 488       16
 604       16
 450       16
 454       16
 447       16
 332       16
 383       16
 503       16
 433       16
 537       16
 308       15
 456       15
 434       15
 487       15
 494       15
 359       15
 489       15
 463       15
 391       15
 355       15
 319       15
 500       15
 490       15
 622       15
 275       15
 378       14
 443       14
 260       14
 464       14
 581       14
 466       14
 504       14
 580       14
 296       14
 527       14
 452       14
 292       14
 592       14
 518       14
 326       14
 493       14
 474       13
 336       13
 299       13
 495       13
 637       13
 455       13
 347       13
 300       13
 551       13
 422       13
 351       13
 320       13
 409       13
 431       12
 436       12
 557       12
 473       12
 471       12
 277       12
 315       12
 453       12
 365       11
 479       11
 467       11
 638       11
 615       11
 284       11
 303       11
 381       11
 612       11
 306       11
 356       11
 534       11
 366       10
 363       10
 502       10
 519       10
 294       10
 238       10
 438       10
 538       10
 483       10
 327       10
 282       10
 710       10
 532       10
 311       10
 491       10
 601       10
 304        9
 484        9
 587        9
 461        9
 507        9
 276        9
 611        9
 497        9
 469        9
 348        9
 572        9
 290        9
 472        9
 329        9
 352        9
 525        8
 675        8
 555        8
 556        8
 501        8
 280        8
 129        8
 548        8
 552        8
 283        8
 265        8
 364        8
 278        8
 237        8
 269        8
 211        8
 596        8
 560        8
 273        8
 511        8
 520        8
 223        7
 529        7
 411        7
 588        7
 570        7
 512        7
 279        7
 582        7
 505        7
 247        7
 574        7
 564        7
 222        7
 485        7
 515        7
 435        7
 506        6
 671        6
 526        6
 533        6
 562        6
 608        6
 549        6
 547        6
 224        6
 613        6
 697        6
 747        6
 676        6
 546        6
 270        6
 571        6
 524        6
 531        6
 508        6
 569        6
 628        6
 331        6
 451        6
 620        5
 266        5
 264        5
 566        5
 255        5
 539        5
 669        5
 577        5
 200        5
 215        5
 595        5
 380        5
 623        5
 553        5
 242        5
 558        5
 626        5
 578        5
 496        5
 576        5
 209        5
 268        5
 565        5
 720        5
 259        5
 133        4
 239        4
 630        4
 684        4
 579        4
 257        4
 261        4
 516        4
 627        4
 514        4
 617        4
 244        4
 178        4
 696        4
 179        4
 522        4
 258        4
 256        4
 634        4
 263        4
 618        4
 267        4
 692        4
 679        4
 609        4
 528        4
 198        3
 91         3
 536        3
 540        3
 641        3
 805        3
 196        3
 544        3
 716        3
 212        3
 253        3
 243        3
 272        3
 158        3
 542        3
 225        3
 686        3
 568        3
 646        3
 847        3
 614        3
 274        3
 586        3
 688        3
 605        3
 81         3
 559        3
 625        3
 643        3
 645        3
 610        3
 584        3
 249        3
 606        3
 639        3
 742        3
 218        3
 633        2
 718        2
 704        2
 229        2
 40         2
 492        2
 740        2
 721        2
 221        2
 711        2
 545        2
 104        2
 731        2
 252        2
 543        2
 677        2
 513        2
 251        2
 51         2
 227        2
 535        2
 717        2
 262        2
 607        2
 602        2
 650        2
 647        2
 254        2
 188        2
 541        2
 763        2
 600        2
 680        2
 210        2
 228        2
 681        2
 233        2
 130        1
 619        1
 84         1
 698        1
 112        1
 217        1
 226        1
 184        1
 672        1
 662        1
 674        1
 661        1
 659        1
 183        1
 230        1
 530        1
 652        1
 214        1
 683        1
 171        1
 189        1
 194        1
 594        1
 624        1
 724        1
 250        1
 762        1
 241        1
 220        1
 206        1
 678        1
 668        1
 169        1
 664        1
 723        1
 561        1
 567        1
 583        1
 790        1
 591        1
 656        1
 727        1
 37         1
 636        1
 599        1
 563        1
 590        1
 246        1
 101        1
 593        1
 801        1
 663        1
 87         1
 138        1
 170        1
 248        1
Name: co2, dtype: int64

In [84]:
df_notnulls.isna().sum().sort_values(ascending=False).head()

drive        1189
cylinders     123
displ         120
trany          11
barrels08       0
dtype: int64

In [67]:
df_notnulls.drive.value_counts(normalize=True)

Front-Wheel Drive             0.362471
Rear-Wheel Drive              0.352786
4-Wheel or All-Wheel Drive    0.181372
All-Wheel Drive               0.056119
4-Wheel Drive                 0.029055
2-Wheel Drive                 0.013832
Part-time 4-Wheel Drive       0.004338
2-Wheel Drive, Front          0.000027
Name: drive, dtype: float64

In [83]:
df_notnulls.cylinders.value_counts(normalize=True).sort_index()

2.0     0.001432
3.0     0.005488
4.0     0.384040
5.0     0.020308
6.0     0.349523
8.0     0.219857
10.0    0.004056
12.0    0.015085
16.0    0.000212
Name: cylinders, dtype: float64

In [82]:
(df_notnulls.displ.value_counts(normalize=True)*100).sort_index()

0.0    0.005302
0.6    0.007953
0.9    0.010604
1.0    0.437399
1.1    0.031811
1.2    0.108687
1.3    0.498370
1.4    0.548737
1.5    1.887443
1.6    3.955147
1.7    0.201469
1.8    4.188426
1.9    1.108077
2.0    9.376243
2.1    0.280996
2.2    3.660897
2.3    2.982265
2.4    5.092384
2.5    6.272036
2.6    0.901307
2.7    1.293640
2.8    2.616441
2.9    0.524879
3.0    7.836068
3.1    0.675980
3.2    1.407629
3.3    1.129285
3.4    1.142539
3.5    3.859714
3.6    2.401718
3.7    1.489807
3.8    2.597885
3.9    0.827082
4.0    2.627045
4.1    0.251836
4.2    1.420884
4.3    3.631737
4.4    0.811176
4.5    0.238581
4.6    1.500411
4.7    0.988787
4.8    0.702489
4.9    0.933118
5.0    3.851762
5.2    1.447393
5.3    2.120722
5.4    0.816478
5.5    0.546086
5.6    0.469210
5.7    2.836466
5.8    0.424144
5.9    0.896005
6.0    1.110728
6.1    0.063622
6.2    1.699229
6.3    0.116640
6.4    0.082178
6.5    0.299552
6.6    0.053018
6.7    0.182912
6.8    0.368475
7.0    0.026509
7.4    0.010604
8.0    0.060971
8.3    0.023858
8.4    0.029160
Name: displ, dtype: float64

1. Media de displ por Marca
2. 'Tesla', 'CODA Automotive', 'Azure Dynamics' tem TODOS os displ NaN
3. Essas marcasd representam 36 linhas
4. Porem temos 120 displ NaN (ou seja, temos outras marcas com displ NaN)
5. EURECA: Todos os 36 tem mesmo fuelType >> Electricity
6. Vimos que dos 120 eletricos(independente de marca), 118 estao Nulos e 2 zerados
7. Tinhamos 120 displ NaN, 118 são por serem eletricos, quais sao os outros 2?

In [85]:
df_notnulls.groupby(['make'])['displ'].mean()

make
AM General                            3.350000
ASC Incorporated                      3.800000
Acura                                 2.834768
Alfa Romeo                            2.528889
American Motors Corporation           3.696296
Aston Martin                          5.322535
Audi                                  2.850545
Aurora Cars Ltd                       4.900000
Autokraft Limited                     4.925000
Avanti Motor Corporation              5.000000
Azure Dynamics                             NaN
BMW                                   3.228580
BMW Alpina                            4.533333
BYD                                   0.000000
Bentley                               6.084483
Bertone                               1.500000
Bill Dovell Motor Car Company         2.300000
Bitter Gmbh and Co. Kg                3.360000
Bugatti                               8.000000
Buick                                 3.304127
CCC Engineering                       5.700000
CODA Automotive                            NaN
CX Automotive                         2.764706
Cadillac                              4.244886
Chevrolet                             4.096596
Chrysler                              3.016074
Consulier Industries Inc              2.200000
Dabryan Coach Builders Inc            4.966667
Dacia                                 1.400000
Daewoo                                1.855224
Daihatsu                              1.264706
Dodge                                 3.867476
E. P. Dutton, Inc.                    4.100000
Eagle                                 2.131056
Environmental Rsch and Devp Corp      2.900000
Evans Automobiles                     5.700000
Excalibur Autos                       5.000000
Federal Coach                         5.228571
Ferrari                               4.751659
Fiat                                  1.446512
Fisker                                2.000000
Ford                                  3.735157
GMC                                   4.711437
General Motors                        5.000000
Genesis                               4.171429
Geo                                   1.454422
Goldacre                              2.500000
Grumman Allied Industries             2.500000
Grumman Olson                         1.600000
Honda                                 2.138295
Hummer                                4.100000
Hyundai                               2.358797
Import Foreign Auto Sales Inc         1.000000
Import Trade Services                 2.469231
Infiniti                              3.708023
Isis Imports Ltd                      3.900000
Isuzu                                 2.717972
J.K. Motors                           3.361111
JBA Motorcars, Inc.                   3.000000
Jaguar                                4.022636
Jeep                                  3.384416
Kenyon Corporation Of America         5.000000
Kia                                   2.351927
Laforza Automobile Inc                4.900000
Lambda Control Systems                3.000000
Lamborghini                           5.659813
Land Rover                            3.919310
Lexus                                 3.615869
Lincoln                               3.873852
London Coach Co Inc                   2.300000
London Taxi                           2.400000
Lotus                                 2.700000
MINI                                  1.631875
Mahindra                              2.200000
Maserati                              3.590435
Maybach                               5.677419
Mazda                                 2.379365
McLaren Automotive                    3.800000
Mcevoy Motors                         2.300000
Mercedes-Benz                         4.040545
Mercury                               3.002463
Merkur                                2.471429
Mitsubishi                            2.442689
Mobility Ventures LLC                 4.600000
Morgan                                3.966667
Nissan                                2.959925
Oldsmobile                            3.248701
PAS Inc - GMC                         4.300000
PAS, Inc                              4.300000
Pagani                                6.000000
Panos                                 4.900000
Panoz Auto-Development                5.000000
Panther Car Company Limited           2.300000
Peugeot                               2.166327
Pininfarina                           2.000000
Plymouth                              2.369905
Pontiac                               2.992833
Porsche                               3.599314
Quantum Technologies                  2.200000
Qvale                                 4.600000
Ram                                   4.191228
Red Shift Ltd.                        2.000000
Renault                               1.771429
Rolls-Royce                           6.705780
Roush Performance                     5.090566
Ruf Automobile Gmbh                   3.400000
S and S Coach Company  E.p. Dutton    6.000000
SRT                                   8.400000
Saab                                  2.298148
Saleen                                5.260000
Saleen Performance                    5.160000
Saturn                                2.329496
Scion                                 2.042169
Shelby                                4.600000
Spyker                                4.200000
Sterling                              2.633333
Subaru                                2.197579
Superior Coaches Div E.p. Dutton      6.000000
Suzuki                                1.964078
TVR Engineering Ltd                   2.800000
Tecstar, LP                           5.400000
Tesla                                      NaN
Texas Coach Company                   5.000000
Toyota                                2.731485
VPG                                   4.600000
Vector                                5.850000
Vixen Motor Company                   2.400000
Volga Associated Automobile           1.600000
Volkswagen                            2.210872
Volvo                                 2.494327
Wallace Environmental                 4.315625
Yugo                                  1.200000
smart                                 0.980000
Name: displ, dtype: float64

In [89]:
df_notnulls['make'].isin(['Tesla', 'CODA Automotive', 'Azure Dynamics']).value_counts()

False    37807
True        36
Name: make, dtype: int64

In [90]:
mask = df_notnulls['make'].isin(['Tesla', 'CODA Automotive', 'Azure Dynamics'])
df_notnulls[mask]

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
24051,0.324,0.0,0.0,8.0,62,61.9000,0,0.0,0.0,55.0,0.0,0,-1,0.0,0.0,62,62.0000,0,0.0,54.0,0.0,0.0,NaN,NaN,Front-Wheel Drive,1,-1,1050,0,Electricity,Electricity,-1,-1,62,62.0000,0,0.0,0.0,54.0,0.0,0,0,31893,0,0,Azure Dynamics,Transit Connect Electric Van,N,False,0,0,56,56.7812,0.0,55.6759,0.0,Automatic (A1),88.4,0.0,88.6,0.0,Special Purpose Vehicle 2WD,2012,1500,0.00,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,0,0,0
24052,0.324,0.0,0.0,8.0,62,61.9000,0,0.0,0.0,55.0,0.0,0,-1,0.0,0.0,62,62.0000,0,0.0,54.0,0.0,0.0,NaN,NaN,Front-Wheel Drive,2,-1,1050,0,Electricity,Electricity,-1,-1,62,62.0000,0,0.0,0.0,54.0,0.0,0,0,31894,0,0,Azure Dynamics,Transit Connect Electric Wagon,N,False,0,0,56,56.7812,0.0,55.6759,0.0,Automatic (A1),88.4,0.0,88.6,0.0,Special Purpose Vehicle 2WD,2012,1500,0.00,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,0,0,0
24473,0.276,0.0,0.0,6.0,77,77.2000,0,0.0,0.0,44.0,0.0,0,-1,0.0,0.0,73,72.7000,0,0.0,46.0,0.0,0.0,NaN,NaN,Front-Wheel Drive,1,-1,900,0,Electricity,Electricity,-1,-1,68,67.9000,0,0.0,0.0,50.0,0.0,0,0,32277,0,14,CODA Automotive,CODA,N,False,0,72,88,93.5550,0.0,93.5550,0.0,Automatic (A1),110.3,0.0,97.0,0.0,Subcompact Cars,2012,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,0,0,0
24784,0.228,0.0,0.0,12.0,88,87.9000,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,89,88.8000,0,0.0,38.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,1,-1,750,0,Electricity,Electricity,-1,-1,90,90.1000,0,0.0,0.0,37.0,0.0,26,94,32557,0,0,Tesla,Model S,Y,False,0,0,265,262.6900,0.0,266.7800,0.0,Automatic (A1),110.4,0.0,113.2,0.0,Large Cars,2012,3000,0.00,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,0,0,0
25650,0.276,0.0,0.0,6.0,77,77.2000,0,0.0,0.0,44.0,0.0,0,-1,0.0,0.0,73,72.7000,0,0.0,46.0,0.0,0.0,NaN,NaN,Front-Wheel Drive,1,10,900,0,Electricity,Electricity,10,-1,68,67.9000,0,0.0,0.0,50.0,0.0,0,0,33337,0,14,CODA Automotive,CODA,N,False,0,72,88,93.5550,0.0,81.2980,0.0,Automatic (A1),110.3,0.0,97.0,0.0,Subcompact Cars,2013,2250,0.00,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,0,0,0
25683,0.210,0.0,0.0,10.0,94,94.4000,0,0.0,0.0,36.0,0.0,0,-1,0.0,0.0,95,95.4000,0,0.0,35.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,2,10,700,0,Electricity,Electricity,10,-1,97,96.7000,0,0.0,0.0,35.0,0.0,26,94,33367,0,0,Tesla,Model S (60 kW-hr battery pack),N,False,0,0,208,205.7000,0.0,210.7000,0.0,Automatic (A1),118.6,0.0,121.5,0.0,Large Cars,2013,3250,3.75,Tue Jan 01 00:00:00 EST 2013,Thu Nov 20 00:00:00 EST 2014,0,0,0
25684,0.228,0.0,0.0,12.0,88,87.9000,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,89,88.8000,0,0.0,38.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,1,10,750,0,Electricity,Electricity,10,-1,90,90.1000,0,0.0,0.0,37.0,0.0,26,94,33368,0,0,Tesla,Model S (85 kW-hr battery pack),Y,False,0,0,265,262.7000,0.0,266.8000,0.0,Automatic (A1),110.4,0.0,113.2,0.0,Large Cars,2013,3000,4.75,Tue Jan 01 00:00:00 EST 2013,Thu Nov 20 00:00:00 EST 2014,0,0,0
25955,0.216,0.0,0.0,6.0,93,93.4000,0,0.0,0.0,36.0,0.0,0,-1,0.0,0.0,94,94.3000,0,0.0,36.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,3,10,700,0,Electricity,Electricity,10,-1,96,95.5000,0,0.0,0.0,35.0,0.0,26,94,33612,0,0,Tesla,Model S (40 kW-hr battery pack),N,False,0,0,139,138.5000,0.0,140.7000,0.0,Automatic (A1),117.3,0.0,120.0,0.0,Large Cars,2013,3250,2.50,Tue Jan 01 00:00:00 EST 2013,Fri Apr 11 00:00:00 EDT 2014,0,0,0
27226,0.228,0.0,0.0,12.0,88,87.9000,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,89,88.8000,0,0.0,38.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,1,10,750,0,Electricity,Electricity,10,-1,90,90.1000,0,0.0,0.0,37.0,0.0,26,94,34775,0,0,Tesla,Model S (85 kW-hr battery pack),N,False,0,0,265,262.7000,0.0,266.8000,0.0,Automatic (A1),110.4,0.0,113.2,0.0,Large Cars,2014,3000,4.75,Mon Mar 10 00:00:00 EDT 2014,Thu Jan 22 00:00:00 EST 2015,0,0,0
27227,0.210,0.0,0.0,10.0,94,94.4000,0,0.0,0.0,36.0,0.0,0,-1,0.0,0.0,95,95.4000,0,0.0,35.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,2,10,700,0,Electricity,Electricity,10,-1,97,96.7000,0,0.0,0.0,35.0,0.0,26,94,34776,0,0,Tesla,Model S (60 kW-hr battery pack),N,False,0,0,208,205.7000,0.0,210.7000,0.0,Automatic (A1),118.6,0.0,121.5,0.0,Large Cars,2014,3250,3.75,Mon Mar 10 00:00:00 EDT 2014,Thu Jan 22 00:00:00 EST 2015,0,0,0
28560,0.228,0.0,0.0,12.0,88,87.9000,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,89,88.8000,0,0.0,38.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,1,10,750,0,Electricity,Electricity,10,-1,90,90.1000,0,0.0,0.0,37.0,0.0,26,94,35980,0,0,Tesla,Model S (85 kW-hr battery pack),N,False,0,0,265,262.7000,0.0,266.8000,0.0,Automatic (A1),110.4,0.0,113.2,0.0,Large Cars,2015,3000,4.75,Tue Jan 06 00:00:00 EST 2015,Wed Apr 22 00:00:00 EDT 2015,0,0,0
28575,0.228,0.0,0.0,12.0,86,86.0000,0,0.0,0.0,39.0,0.0,0,-1,0.0,0.0,89,89.3000,0,0.0,38.0,0.0,0.0,NaN,NaN,4-Wheel Drive,4,10,750,0,Electricity,Electricity,10,-1,94,93.7000,0,0.0,0.0,36.0,0.0,26,94,35994,0,0,Tesla,Model S AWD (85 kW-hr battery pack),N,False,0,0,242,233.5000,0.0,253.2000,0.0,Automatic (A1),117.8,0.0,128.4,0.0,Large Cars,2014,3000,4.75,Mon Jan 12 00:00:00 EST 2015,Thu Jan 22 00:00:00 EST 2015,0,0,0
28591,0.216,0.0,0.0,12.0,89,89.3714,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,93,92.9112,0,0.0,36.0,0.0,0.0,NaN,NaN,All-Wheel Drive,4,10,700,0,Electricity,Electricity,10,-1,98,97.6374,0,0.0,0.0,35.0,0.0,26,94,36008,0,0,Tesla,Model S AWD - P85D,N,False,0,0,253,242.3000,0.0,265.5000,0.0,Automatic (A1),121.1,0.0,132.3,0.0,Large Cars,2015,3250,4.75,Thu Jan 22 00:00:00 EST 2015,Wed Aug 12 00:00:00 EDT 2015,0,0,0
28592,0.204,0.0,0.0,12.0,95,95.3056,0,0.0,0.0,35.0,0.0,0,-1,0.0,0.0,100,99.8433,0,0.0,34.0,0.0,0.0,NaN,NaN,All-Wheel Drive,5,10,650,0,Electricity,Electricity,10,-1,106,106.0124,0,0.0,0.0,32.0,0.0,26,94,36009,0,0,Tesla,Model S AWD - 85D,N,False,0,0,270,257.1000,0.0,285.3000,0.0,Automatic (A1),126.4,0.0,140.6,0.0,Large Cars,2015,3500,4.75,Thu Jan 22 00:00:00 EST 2015,Wed Aug 12 00:00:00 EDT 2015,0,0,0
28600,0.210,0.0,0.0,10.0,94,94.4056,0,0.0,0.0,36.0,0.0,0,-1,0.0,0.0,95,95.4404,0,0.0,35.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,2,10,700,0,Electricity,Electricity,10,-1,97,96.7140,0,0.0,0.0,35.0,0.0,26,94,36017,0,0,Tesla,Model S (60 kW-hr battery pack),N,False,0,0,208,205.7000,0.0,210.7000,0.0,Automatic (A1),118.6,0.0,121.5,0.0,Large Cars,2015,3250,3.75,Tue Jan 27 00:00:00 EST 2015,Wed Aug 12 00:00:00 EDT 2015,0,0,0
28720,0.198,0.0,0.0,12.0,101,100.8098,0,0.0,0.0,33.0,0.0,0,-1,0.0,0.0,101,101.2486,0,0.0,33.0,0.0,0.0,NaN,NaN,All-Wheel Drive,6,10,650,0,Electricity,Electricity,10,-1,102,101.7900,0,0.0,0.0,33.0,0.0,26,94,36126,0,0,Tesla,Model S AWD - 70D,N,False,0,0,240,242.8000,0.0,246.4000,0.0,Automatic (A1),133.7,0.0,135.0,0.0,Large Cars,2015,3500,4.75,Mon Apr 06 00:00:00 EDT 2015,Wed Aug 12 00:00:00 EDT 2015,0,0,0
29443,0.204,0.0,0.0,12.0,95,95.3056,0,0.0,0.0,35.0,0.0,0,-1,0.0,0.0,100,99.8433,0,0.0,34.0,0.0,0.0,NaN,NaN,All-Wheel Drive,7,10,650,0,Electricity,Electricity,10,-1,106,106.0124,0,0.0,0.0,32.0,0.0,26,94,36786,0,0,Tesla,Model S AWD - 90D,N,False,0,0,270,257.1000,0.0,285.3000,0.0,Automatic (A1),126.4,0.0,140.6,0.0,Large Cars,2015,3500,4.75,Thu Aug 06 00:00:00 EDT 2015,Wed Aug 12 00:00:00 EDT 2015,0,0,0
29444,0.216,0.0,0.0,12.0,89,89.3714,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,93,92.9112,0,0.0,36.0,0.0,0.0,NaN,NaN,All-Wheel Drive,8,10,700,0,Electricity,Electricity,10,-1,98,97.6374,0,0.0,0.0,35.0,0.0,26,94,36787,0,0,Tesla,Model S AWD - P90D,N,False,0,0,253,242.3000,0.0,265.5000,0.0,Automatic (A1),121.1,0.0,132.3,0.0,Large Cars,2015,3250,4.75,Thu Aug 06 00:00:00 EDT 2015,Wed Aug 12 00:00:00 EDT 2015,0,0,0
29652,0.222,0.0,0.0,12.0,90,90.2795,0,0.0,0.0,37.0,0.0,0,-1,0.0,0.0,92,92.0840,0,0.0,37.0,0.0,0.0,NaN,NaN,All-Wheel Drive,9,10,700,0,Electricity,Electricity,10,-1,94,94.3898,0,0.0,0.0,36.0,0.0,26,94,36979,0,0,Tesla,Model X AWD - 90D,N,False,0,0,257,252.4000,0.0,262.7000,0.0,Automatic (A1),123.0,0.0,132.6,0.0,Standard Sport Utility Vehicle 4WD,2016,3250,4.75,Fri Sep 25 00:00:00 EDT 2015,Tue Jan 05 00:00:00 EST 2016,0,0,0
29654,0.228,0.0,0.0,12.0,89,88.5914,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,89,89.1811,0,0.0,38.0,0.0,0.0,NaN,NaN,All-Wheel Drive,10,10,750,0,Electricity,Electricity,10,-1,90,89.9126,0,0.0,0.0,37.0,0.0,26,94,36980,0,0,Tesla,Model X AWD - P90D,N,False,0,0,250,247.3000,0.0,252.7000,0.0,Automatic (A1),120.7,0.0,122.5,0.0,Standard Sport Utility Vehicle 4WD,2016,3000,4.75,Fri Sep 25 00:00:00 EDT 2015,Tue Jan 05 00:00:00 EST 2016,0,0,0
29933,0.228,0.0,0.0,10.0,88,87.8784,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,89,88.8676,0,0.0,38.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,3,10,750,0,Electricity,Electricity,10,-1,90,90.1072,0,0.0,0.0,37.0,0.0,26,94,37233,0,0,Tesla,Model S (70 kW-hr battery pack),N,False,0,0,234,234.0000,0.0,234.3000,0.0,Automatic (A1),110.4,0.0,113.2,0.0,Large Cars,2016,3000,3.75,Thu Jan 21 00:00:00 EST 2016,Wed Mar 02 00:00:00 EST 2016,0,0,0
29934,0.228,0.0,0.0,12.0,88,87.9000,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,89,88.8000,0,0.0,38.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,1,10,750,0,Electricity,Electricity,10,-1,90,90.1000,0,0.0,0.0,37.0,0.0,26,94,37234,0,0,Tesla,Model S (85 kW-hr battery pack),N,False,0,0,265,262.7000,0.0,266.8000,0.0,Automatic (A1),110.4,0.0,113.2,0.0,Large Cars,2016,3000,4.75,Thu Jan 21 00:00:00 EST 2016,Wed Mar 02 00:00:00 EST 2016,0,0,0
29935,0.228,0.0,0.0,12.0,88,87.8784,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,89,88.8876,0,0.0,38.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,71,10,750,0,Electricity,Electricity,10,-1,90,90.1072,0,0.0,0.0,37.0,0.0,26,94,37235,0,0,Tesla,Model S (90 kW-hr battery pack),N,False,0,0,265,262.7000,0.0,266.8000,0.0,Automatic (A1),110.4,0.0,113.2,0.0,Large Cars,2016,3000,4.75,Thu Jan 21 00:00:00 EST 2016,Wed Mar 02 00:00:00 EST 2016,0,0,0
29936,0.228,0.0,0.0,12.0,88,87.8784,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,89,88.8876,0,0.0,38.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,71,10,750,0,Electricity,Electricity,10,-1,90,90.1072,0,0.0,0.0,37.0,0.0,26,94,37236,0,0,Tesla,Model S (90 kW-hr battery pack),N,False,0,0,265,262.7000,0.0,266.8000,0.0,Automatic (A1),110.4,0.0,113.2,0.0,Large Cars,2015,3000,4.75,Thu Jan 21 00:00:00 EST 2016,Thu Jan 21 00:00:00 EST 2016,0,0,0
29938,0.198,0.0,0.0,12.0,101,100.8098,0,0.0,0.0,33.0,0.0,0,-1,0.0,0.0,101,101.2486,0,0.0,33.0,0.0,0.0,NaN,NaN,All-Wheel Drive,6,10,650,0,Electricity,Electricity,10,-1,102,101.7900,0,0.0,0.0,33.0,0.0,26,94,37238,0,0,Tesla,Model S AWD - 70D,N,False,0,0,240,242.8000,0.0,246.4000,0.0,Automatic (A1),133.7,0.0,135.0,0.0,Large Cars,2016,3500,4.75,Thu Jan 28 00:00:00 EST 2016,Wed Mar 02 00:00:00 EST 2016,0,0,0
29939,0.204,0.0,0.0,12.0,95,95.3056,0,0.0,0.0,35.0,0.0,0,-1,0.0,0.0,100,99.8433,0,0.0,34.0,0.0,0.0,NaN,NaN,All-Wheel Drive,5,10,650,0,Electricity,Electricity,10,-1,106,106.0124,0,0.0,0.0,32.0,0.0,26,94,37239,0,0,Tesla,Model S AWD - 85D,N,False,0,0,270,257.1000,0.0,285.3000,0.0,Automatic (A1),126.4,0.0,140.6,0.0,Large Cars,2016,3500,4.75,Thu Jan 28 00:00:00 EST 2016,Wed Mar 02 00:00:00 EST 2016,0,0,0
29941,0.198,0.0,0.0,12.0,101,100.8065,0,0.0,0.0,33.0,0.0,0,-1,0.0,0.0,103,103.3087,0,0.0,33.0,0.0,0.0,NaN,NaN,All-Wheel Drive,7,10,650,0,Electricity,Electricity,10,-1,107,106.5410,0,0.0,0.0,32.0,0.0,26,94,37240,0,0,Tesla,Model S AWD - 90D,N,False,0,0,294,285.7000,0.0,303.2000,0.0,Automatic (A1),133.6,0.0,141.2,0.0,Large Cars,2016,3500,4.75,Thu Jan 28 00:00:00 EST 2016,Wed Apr 20 00:00:00 EDT 2016,0,0,0
29942,0.216,0.0,0.0,12.0,89,89.3714,0,0.0,0.0,38.0,0.0,0,-1,0.0,0.0,93,92.9112,0,0.0,36.0,0.0,0.0,NaN,NaN,All-Wheel Drive,4,10,700,0,Electricity,Electricity,10,-1,98,97.6374,0,0.0,0.0,35.0,0.0,26,94,37241,0,0,Tesla,Model S AWD - P85D,N,False,0,0,253,242.3000,0.0,265.5000,0.0,Automatic (A1),121.1,0.0,132.3,0.0,Large Cars,2016,3250,4.75,Thu Jan 28 00:00:00 EST 2016,Wed Mar 02 00:00:00 EST 2016,0,0,0
29943,0.210,0.0,0.0,12.0,91,91.3191,0,0.0,0.0,37.0,0.0,0,-1,0.0,0.0,95,94.9536,0,0.0,35.0,0.0,0.0,NaN,NaN,All-Wheel Drive,8,10,700,0,Electricity,Electricity,10,-1,100,99.8087,0,0.0,0.0,34.0,0.0,26,94,37242,0,0,Tesla,Model S AWD - P90D,N,False,0,0,270,259.6000,0.0,283.4000,0.0,Automatic (A1),123.7,0.0,135.2,0.0,Large Cars,2016,3250,4.75,Thu Jan 28 00:00:00 EST 2016,Tue Apr 26 00:00:00 EDT 2016,0,0,0
30141,0.204,0.0,0.0,12.0,97,97.4898,0,0.0,0.0,35.0,0.0,0,-1,0.0,0.0,98,98.4090,0,0.0,34.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,31,10,650,0,Electricity,Electricity,10,-1,100,99.5562,0,0.0,0.0,34.0,0.0,26,94,37421,0,0,Tesla,Model S (75 kW-hr battery pack),N,False,0,0,249,246.1000,0.0,252.7000,0.0,Automatic (A1),132.1,0.0,134.9,0.0,Large Cars,2016,3500,4.75,Wed May 04 00:00:00 EDT 2016,Wed May 04 00:00:00 EDT 2016,0,0,0
30142,0.198,0.0,0.0,12.0,102,101.7702,0,0.0,0.0,33.0,0.0,0,-1,0.0,0.0,103,103.3343,0,0.0,33.0,0.0,0.0,NaN,NaN,All-Wheel Drive,61,10,650,0,Electricity,Electricity,10,-1,105,105.3126,0,0.0,0.0,32.0,0.0,26,94,37422,0,0,Tesla,Model S AWD - 75D,N,False,0,0,259,255.0000,0.0,264.6000,0.0,Automatic (A1),137.9,0.0,142.7,0.0,Large Cars,2016,3500,4.75,Wed May 04 00:00:00 EDT 2016,Wed May 04 00:00:00 EDT 2016,0,0,0
30143,0.216,0.0,0.0,12.0,91,91.1628,0,0.0,0.0,37.0,0.0,0,-1,0.0,0.0,93,93.0305,0,0.0,36.0,0.0,0.0,NaN,NaN,All-Wheel Drive,11,10,700,0,Electricity,Electricity,10,-1,95,95.4200,0,0.0,0.0,35.0,0.0,26,94,37423,0,0,Tesla,Model X AWD - 75D,N,False,0,0,238,233.7000,0.0,242.2000,0.0,Automatic (A1),124.2,0.0,130.0,0.0,Standard Sport Utility Vehicle 4WD,2016,3250,4.75,Wed May 04 00:00:00 EDT 2016,Wed May 04 00:00:00 EDT 2016,0,0,0
30972,0.204,0.0,0.0,10.0,98,97.5636,0,0.0,0.0,35.0,0.0,0,-1,0.0,0.0,99,99.0945,0,0.0,34.0,0.0,0.0,NaN,NaN,Rear-Wheel Drive,2,10,650,0,Electricity,Electricity,10,-1,101,101.0322,0,0.0,0.0,33.0,0.0,26,94,38170,0,0,Tesla,Model S (60 kW-hr battery pack),N,False,0,0,210,207.5000,0.0,214.8000,0.0,Automatic (A1),132.2,0.0,136.9,0.0,Large Cars,2016,3500,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30973,0.192,0.0,0.0,12.0,101,101.4750,0,0.0,0.0,33.0,0.0,0,-1,0.0,0.0,104,103.7678,0,0.0,32.0,0.0,0.0,NaN,NaN,All-Wheel Drive,21,10,600,0,Electricity,Electricity,10,-1,107,106.7148,0,0.0,0.0,32.0,0.0,26,94,38171,0,0,Tesla,Model S AWD - 60D,N,False,0,0,218,221.1000,0.0,226.9000,0.0,Automatic (A1),137.5,0.0,144.6,0.0,Large Cars,2016,3750,3.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30974,0.210,0.0,0.0,12.0,92,92.4713,0,0.0,0.0,36.0,0.0,0,-1,0.0,0.0,98,97.5232,0,0.0,35.0,0.0,0.0,NaN,NaN,All-Wheel Drive,15,10,700,0,Electricity,Electricity,10,-1,105,104.5008,0,0.0,0.0,32.0,0.0,26,94,38172,0,0,Tesla,Model S AWD - P100D,N,False,0,0,315,305.9000,0.0,346.9000,0.0,Automatic (A1),125.3,0.0,141.6,0.0,Large Cars,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0
30975,0.216,0.0,0.0,12.0,91,91.2362,0,0.0,0.0,37.0,0.0,0,-1,0.0,0.0,93,92.5663,0,0.0,36.0,0.0,0.0,NaN,NaN,All-Wheel Drive,12,10,700,0,Electricity,Electricity,10,-1,94,94.2456,0,0.0,0.0,36.0,0.0,26,94,38173,0,0,Tesla,Model X AWD - 60D,N,False,0,0,200,196.5000,0.0,203.2000,0.0,Automatic (A1),124.3,0.0,128.4,0.0,Standard Sport Utility Vehicle 4WD,2016,3250,4.75,Tue Sep 13 00:00:00 EDT 2016,Tue Sep 13 00:00:00 EDT 2016,0,0,0

In [94]:
df_notnulls.groupby('fuelType1')['fuelType1'].count()

fuelType1
Diesel                1101
Electricity            120
Midgrade Gasoline       74
Natural Gas             60
Premium Gasoline     10162
Regular Gasoline     26326
Name: fuelType1, dtype: int64

In [91]:
df_notnulls.groupby('fuelType')['fuelType'].count()

fuelType
CNG                               60
Diesel                          1101
Electricity                      120
Gasoline or E85                 1204
Gasoline or natural gas           20
Gasoline or propane                8
Midgrade                          74
Premium                        10004
Premium Gas or Electricity        17
Premium and Electricity           20
Premium or E85                   121
Regular                        25076
Regular Gas and Electricity       16
Regular Gas or Electricity         2
Name: fuelType, dtype: int64

In [98]:
df_elet = df_notnulls[df_notnulls['fuelType1'] == 'Electricity']
df_elet['displ'].isna().value_counts()

True     118
False      2
Name: displ, dtype: int64

In [99]:
df_elet = df_notnulls[df_notnulls['fuelType1'] == 'Electricity']
df_elet['displ'].value_counts()

0.0    2
Name: displ, dtype: int64

In [100]:
mask_notelet = df_notnulls['fuelType1'] != 'Electricity'
mask_displnan = df_notnulls['displ'].isna()

df_notnulls[mask_notelet & mask_displnan]

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,charge240b,createdOn,modifiedOn,phevCity,phevHwy,phevComb
21413,13.73375,0.0,0.0,0.0,22,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,370.291667,24,0.0,0,0.0,0.0,0.0,0.0,NaN,NaN,4-Wheel Drive,0,-1,1400,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,29472,0,0,Subaru,RX Turbo,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,27.4,0.0,38.8,0.0,Subcompact Cars,1985,-250,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0
21414,14.33087,0.0,0.0,0.0,21,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,NaN,NaN,4-Wheel Drive,0,-1,1450,0,Regular,Regular Gasoline,-1,-1,27,0.0,0,0.0,0.0,0.0,0.0,0,0,29473,0,0,Subaru,RX Turbo,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,26.9,0.0,37.1,0.0,Subcompact Cars,1985,-500,0.0,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,0,0,0

In [104]:
mask_subaru = df_notnulls['make'] == 'Subaru'
mask_model = df_notnulls['model'] == 'RX Turbo'
df_notnulls[mask_subaru].groupby('model')['displ'].unique()

model
3 Door 4WD Turbo                                   [1.8]
B9 Tribeca AWD                                     [3.0]
BRZ                                                [2.0]
Baja AWD                                           [2.5]
Brat 4WD                                           [1.8]
Crosstrek AWD                                      [2.0]
Forester AWD                                  [2.5, 2.0]
Hatchback                                     [1.8, 1.6]
Hatchback 4WD                                      [1.8]
Impreza                                            [1.8]
Impreza AWD                         [1.8, 2.2, 2.5, 2.0]
Impreza Sport AWD                                  [2.0]
Impreza Wagon                                      [1.8]
Impreza Wagon AWD                   [1.8, 2.2, 2.5, 2.0]
Impreza Wagon/Outback SPT AWD                 [2.0, 2.5]
Impreza Wagon/Outback Sport                        [2.5]
Impreza Wagon/Outback Sport AWD               [2.5, 2.0]
Justy                                              [1.2]
Justy 4WD                                          [1.2]
Justy AWD                                          [1.2]
Legacy                                             [2.2]
Legacy 4WD                                         [2.2]
Legacy 4WD Turbo                                   [2.2]
Legacy AWD                          [2.2, 2.5, 3.0, 3.6]
Legacy AWD (incl. Outback)                    [2.5, 3.0]
Legacy AWD Turbo                                   [2.2]
Legacy Turbo                                       [2.2]
Legacy Wagon                                       [2.2]
Legacy Wagon 4WD                                   [2.2]
Legacy Wagon AWD                         [2.2, 2.5, 3.0]
Legacy Wagon AWD (incl. Outback)              [2.5, 3.0]
Legacy Wagon AWD Turbo                             [2.2]
Legacy/Outback AWD                            [2.5, 3.0]
Legacy/Outback Wagon AWD                      [2.5, 3.0]
Loyale                                             [1.8]
Loyale 4WD                                         [1.8]
Loyale 4WD Turbo                                   [1.8]
Loyale AWD                                         [1.8]
Loyale Wagon                                       [1.8]
Loyale Wagon 4WD                                   [1.8]
Loyale Wagon 4WD Turbo                             [1.8]
Loyale Wagon AWD                                   [1.8]
Outback AWD                              [3.0, 2.5, 3.6]
Outback Wagon AWD                        [2.5, 3.0, 3.6]
RX Turbo                                           [nan]
SVX                                                [3.3]
SVX AWD                                            [3.3]
Sedan                                         [1.8, 1.6]
Sedan 4WD                                          [1.8]
Sedan/3 Door                                       [1.8]
Sedan/3 Door 4WD                                   [1.8]
Sedan/3Door 4WD Turbo                              [1.8]
Tribeca AWD                                        [3.6]
WRX                                           [2.0, 2.5]
Wagon                                              [1.8]
Wagon 4WD                                          [1.8]
Wagon 4WD Turbo                                    [1.8]
XT                                            [1.8, 2.7]
XT 4WD                                        [1.8, 2.7]
XT-DL                                              [1.8]
XV Crosstrek AWD                                   [2.0]
XV Crosstrek Hybrid AWD                            [2.0]
Name: displ, dtype: object

In [108]:
mask_subaru = df_notnulls['make'] == 'Subaru'
mask_model = df_notnulls['model'] == 'RX Turbo'

df_notnulls['displ_ajust'] = df_notnulls['displ']
df_notnulls.loc[mask_subaru & mask_model, 'displ_ajust'] = 1.8
# df_notnulls.loc[~(mask_subaru & mask_model), 'displ_ajust'] = 2.0

In [112]:
df_notnulls['displ_ajust'].isna().value_counts()

False    37725
True       118
Name: displ_ajust, dtype: int64

In [113]:
df_notnulls['displ_ajust'] = df_notnulls['displ_ajust'].fillna(0)

In [114]:
df_notnulls['displ_ajust'].isna().value_counts()

False    37843
Name: displ_ajust, dtype: int64

## Checking duplicates rows
    
>    - Dropping fully duplicate row
>    - Subset
>    - `.duplicated()`
>    - `.drop_duplicates()`

In [115]:
frutas = pd.DataFrame({
    'fruta':['laranja', 'laranja', 'mamão', 'laranja'],
    'cidade':['Rio de Janeiro', 'Atibaia', 'Campinas', 'Rio de Janeiro']
})

In [116]:
frutas

     fruta          cidade
0  laranja  Rio de Janeiro
1  laranja         Atibaia
2    mamão        Campinas
3  laranja  Rio de Janeiro

In [117]:
frutas.iloc[:3]

     fruta          cidade
0  laranja  Rio de Janeiro
1  laranja         Atibaia
2    mamão        Campinas

In [123]:
frutas.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [122]:
frutas.duplicated(subset=['fruta'])

0    False
1     True
2    False
3     True
dtype: bool

In [127]:
dup2drop = frutas.duplicated(subset=['fruta'], keep='last')
dup2drop

0     True
1     True
2    False
3    False
dtype: bool

In [128]:
frutas[dup2drop]

     fruta          cidade
0  laranja  Rio de Janeiro
1  laranja         Atibaia

In [129]:
frutas[dup2drop].index

Int64Index([0, 1], dtype='int64')

In [130]:
frutas.drop(index=frutas[dup2drop].index)

     fruta          cidade
2    mamão        Campinas
3  laranja  Rio de Janeiro

In [132]:
frutas.drop_duplicates()

     fruta          cidade
0  laranja  Rio de Janeiro
1  laranja         Atibaia
2    mamão        Campinas

In [133]:
frutas.drop_duplicates(subset=['fruta'], keep='last')

     fruta          cidade
2    mamão        Campinas
3  laranja  Rio de Janeiro

In [ ]:
#criar method para DataFrames

In [139]:
from pandas.core.base import PandasObject

In [ ]:
def set_description(df, description):
    df.description = description

In [146]:
PandasObject.set_description = set_description

In [147]:
df_notnulls.set_description('oieee')

In [152]:
df_notnulls.description

'oieee'

In [150]:
df.set_description('Este dataFrame tem dados bagunçados de veiculos')

In [151]:
df.description

'Este dataFrame tem dados bagunçados de veiculos'

In [153]:
df2 = df

In [154]:
df2.description

'Este dataFrame tem dados bagunçados de veiculos'